language: java
script:
- mvn install
os: linux
cache:
    directories:
        - $HOME/.m2
git:
    depth: 1
    submodules: false
jdk:
- oraclejdk14
- openjdk11
- openjdk8
- oraclejdk13
sudo: false
branches:
    only:
    - master
